-- 코드를 입력하세요
SELECT DISTINCT(C.CAR_ID), C.CAR_TYPE, ROUND(C.DAILY_FEE*30*(1-D.DISCOUNT_RATE/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D
ON C.CAR_TYPE = D.CAR_TYPE
WHERE (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')
AND C.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY GROUP BY CAR_ID HAVING MAX(END_DATE) > '2022-11-01')
AND D.DURATION_TYPE = '30일 이상'
AND C.DAILY_FEE*30*(1-D.DISCOUNT_RATE/100) BETWEEN 500000 AND 1990000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;